language: scala

script:
  - ./mill _.compile
  - ./mill _.test

# deploy:
#  skip_cleanup: true
#  provider: script
#  script: ci/deploy.sh
#  on:
#    tags: true

cache:
  directories:
    - $HOME/.coursier
    - $HOME/.mill/download
